version: "3"
services:
 wiremock:
  image: rodolpheche/wiremock:latest
  ports:
    - "8181:8080"
  volumes:
    - ./wiremock/__files/:/./home/wiremock/__files/
    - ./wiremock/mappings/:/./home/wiremock/mappings/
  command:
    - -verbose
    - -global-response-templating